"""Add character column

Revision ID: 2f6f8db4a22b
Revises: 6b0f8ae47395
Create Date: 2021-02-20 18:17:45.640760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6f8db4a22b'
down_revision = '6b0f8ae47395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marvel', sa.Column('character', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marvel', 'character')
    # ### end Alembic commands ###
