"""init

Revision ID: 6b0f8ae47395
Revises: 589a7bdc32e6
Create Date: 2021-02-07 10:13:31.401075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0f8ae47395'
down_revision = '589a7bdc32e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('marvel',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=True),
        sa.Column('description', sa.String(length=150), nullable=True),
        sa.Column('comics_appeared_in', sa.Integer(), nullable=True),
        sa.Column('super_power', sa.String(length=150), nullable=True),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.Column('owner', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['owner'], ['user.token'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('name', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('character', sa.Integer, sa.ForeignKey('marvel.id'), nullable=False))
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=150), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=150), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=150), nullable=True))
    op.drop_column('user', 'name')
    op.drop_column('user', 'character')
    op.drop_table('marvel')
    # ### end Alembic commands ###
